# Generated by Django 5.0.3 on 2024-03-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen_test_app', '0002_scanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanstatus',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
