# Generated by Django 5.0.3 on 2024-03-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen_test_app', '0003_alter_scanstatus_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/')),
                ('scan_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen_test_app.scanstatus')),
            ],
        ),
    ]
